### ISSUE TITLE
 undefined method `call' for {:default=>#<Dry::Container::Registry:0x0000000110f1a570 @_mutex=#<Thread::Mutex:0x0000000110f1a4f8>>}:Hash (NoMethodError)

### ISSUE THREAD

**Issue by eprislac** [scarhand/devise-jwt-cookie#13]
getting this error after installing devise-jwt-cookie (had already previously set up devise-jwt and was working), but cannot even start app now, due to this error (undefined method `call`, coming from dry-configurable
. A little later down the line, I see this: `cannot load such file -- devise-jwt (LoadError)`

ENV: ruby 3.1.1, rails 7, mac & linux both 

full trace:
```
bundler: failed to load command: bin/rails (bin/rails)
/Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/dry-container-0.10.0/lib/dry/container/mixin.rb:151:in `register': undefined method `call' for {:default=>#<Dry::Container::Registry:0x0000000110f1a570 @_mutex=#<Thread::Mutex:0x0000000110f1a4f8>>}:Hash (NoMethodError)


        config.registry.call(_container, key, item, options)
                       ^^^^^
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/dry-auto_inject-0.9.0/lib/dry/auto_inject/strategies/args.rb:72:in `<class:Strategies>'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/dry-auto_inject-0.9.0/lib/dry/auto_inject/strategies/args.rb:8:in `<module:AutoInject>'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/dry-auto_inject-0.9.0/lib/dry/auto_inject/strategies/args.rb:7:in `<module:Dry>'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/dry-auto_inject-0.9.0/lib/dry/auto_inject/strategies/args.rb:6:in `<main>'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/dry-auto_inject-0.9.0/lib/dry/auto_inject/strategies.rb:19:in `<main>'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/dry-auto_inject-0.9.0/lib/dry/auto_inject/builder.rb:3:in `<main>'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/dry-auto_inject-0.9.0/lib/dry/auto_inject.rb:3:in `<main>'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/warden-jwt_auth-0.5.0/lib/warden/jwt_auth.rb:4:in `<main>'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/devise-jwt-0.8.1/lib/devise/jwt.rb:6:in `<main>'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/runtime.rb:73:in `rescue in block in require'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/runtime.rb:51:in `block in require'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/runtime.rb:44:in `each'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/runtime.rb:44:in `require'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler.rb:187:in `require'
        from /Users/eddie/Projects/Paubox/pb_iam/config/application.rb:7:in `<main>'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3.1/lib/rails/command/actions.rb:22:in `require_application!'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3.1/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3.1/lib/rails/commands/console/console_command.rb:101:in `perform'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3.1/lib/rails/command/base.rb:87:in `perform'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3.1/lib/rails/command.rb:48:in `invoke'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3.1/lib/rails/commands.rb:18:in `<main>'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from bin/rails:4:in `<top (required)>'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/cli/exec.rb:58:in `load'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/cli/exec.rb:23:in `run'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/cli.rb:483:in `exec'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/cli.rb:31:in `dispatch'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/cli.rb:25:in `start'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/exe/bundle:48:in `block in <top (required)>'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/exe/bundle:36:in `<top (required)>'
        from /Users/eddie/.rbenv/versions/3.1.1/bin/bundle:25:in `load'
        from /Users/eddie/.rbenv/versions/3.1.1/bin/bundle:25:in `<main>'
/Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require': cannot load such file -- devise-jwt (LoadError)
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/runtime.rb:55:in `each'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/runtime.rb:55:in `block in require'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/runtime.rb:44:in `each'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/runtime.rb:44:in `require'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler.rb:187:in `require'
        from /Users/eddie/Projects/Paubox/pb_iam/config/application.rb:7:in `<main>'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3.1/lib/rails/command/actions.rb:22:in `require_application!'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3.1/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3.1/lib/rails/commands/console/console_command.rb:101:in `perform'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3.1/lib/rails/command/base.rb:87:in `perform'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3.1/lib/rails/command.rb:48:in `invoke'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3.1/lib/rails/commands.rb:18:in `<main>'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from bin/rails:4:in `<top (required)>'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/cli/exec.rb:58:in `load'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/cli/exec.rb:23:in `run'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/cli.rb:483:in `exec'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/cli.rb:31:in `dispatch'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/cli.rb:25:in `start'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/exe/bundle:48:in `block in <top (required)>'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
        from /Users/eddie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/exe/bundle:36:in `<top (required)>'
        from /Users/eddie/.rbenv/versions/3.1.1/bin/bundle:25:in `load'
        from /Users/eddie/.rbenv/versions/3.1.1/bin/bundle:25:in `<main>'
```

**Comment by thczzz** [comment]
Any solutions ?
